#
# @title Build and Commit
# @since 2018/08/07
# @author fujisawa-shin
#

version: 2

defaults: &defaults
  docker:
    - image: circleci/node:12.4-browsers
  working_directory: ~/app
  environment:
    INSTALL_COMMAND: "npm install"
    TEST_COMMAND: "npm test"
    BUILD_COMMAND: "npm run build"
    DOC_ROOT: "dist"
    BUILD_BRANCHI_POSTFIX: "build"

jobs:
  npm_release:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/app/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  build_deploy:
    jobs:
      - npm_release:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/